---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver_config:
      box: ubuntu-14.04
      # box_url: https://nmd-virtualbox.s3-us-west-2.amazonaws.com/nmd-ubunutu-12.04-i386-base-latest.box
      box_url: https://s3-us-west-2.amazonaws.com/nmd-virtualbox/nmd-ubunutu-14.04-x86_64-base.box
suites:
  - name: default
    run_list:
      - recipe[nmddatabase::default]
    data_bags_path: "<%= ENV['DATA_BAGS_PATH'] %>"
    attributes:
  - name: mysqlserver
    run_list:
      - recipe[nmddatabase::mysqlserver]
  - name: createdatabase
    run_list:
      - recipe[nmddatabase::mysqlserver]
      - recipe[nmddatabase::createdatabase]
    attributes: {
      "nmddatabase": {
        "databases": ["example1", "example2"]
      }
    }
  - name: useraccess
    run_list:
      - recipe[nmddatabase::mysqlserver]
      - recipe[nmddatabase::createdatabase]
      - recipe[nmddatabase::useraccess]
    attributes: {
      "nmddatabase": {
        "databases": ["example"]
      }
    }
